//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agentes()
        {
            this.AgentesTarjetas = new HashSet<AgentesTarjetas>();
        }
    
        public int Codigo { get; set; }
        public string CodigoRes { get; set; }
        public string CodigoInt { get; set; }
        public Nullable<int> CodigoMaster { get; set; }
        public string RazonSocial { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Situacion { get; set; }
        public Nullable<short> Tipo { get; set; }
        public string Ruc { get; set; }
        public Nullable<short> TipoAgencia { get; set; }
        public Nullable<short> TipoAgente { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string Frecuencia { get; set; }
        public string Contacto { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string email { get; set; }
        public string Notas { get; set; }
        public string Estado { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string SysPC { get; set; }
        public string Grupo1 { get; set; }
        public string Clase { get; set; }
        public string CtaBancaria { get; set; }
        public Nullable<int> flag { get; set; }
        public string Tour_code { get; set; }
        public Nullable<bool> canEmi { get; set; }
        public Nullable<short> AutoCrear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentesTarjetas> AgentesTarjetas { get; set; }
        public virtual AgentesCuentas AgentesCuentas { get; set; }
    }
}
