//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentesTmp
    {
        public int Codigo { get; set; }
        public string CodigoRes { get; set; }
        public string CodigoInt { get; set; }
        public Nullable<int> CodigoMaster { get; set; }
        public string RazonSocial { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Situacion { get; set; }
        public string Estado { get; set; }
        public Nullable<short> Tipo { get; set; }
        public string Ruc { get; set; }
        public Nullable<short> TipoAgencia { get; set; }
        public Nullable<short> TipoAgente { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<bool> canEmi { get; set; }
        public string Contacto { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string email { get; set; }
        public string email_orden { get; set; }
        public string Notas { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string SysPC { get; set; }
        public string Grupo1 { get; set; }
        public string Clase { get; set; }
        public string CtaBancaria { get; set; }
        public string OfficeId { get; set; }
        public Nullable<short> AutoCrear { get; set; }
        public Nullable<short> AuthOrden { get; set; }
        public string CodigoIata { get; set; }
        public string OfficeIdResi { get; set; }
        public Nullable<int> IdPromotora { get; set; }
        public Nullable<short> Flag { get; set; }
        public string codEstado { get; set; }
    }
}
