//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentesTarjetas
    {
        public int Codigo { get; set; }
        public Nullable<int> Agente { get; set; }
        public string Tarjeta { get; set; }
        public string Establecimiento { get; set; }
    
        public virtual Agentes Agentes { get; set; }
    }
}
