//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PubOrigen
    {
        public string IdOrigen { get; set; }
        public string Orden { get; set; }
        public string NomOrigen { get; set; }
        public Nullable<bool> IdBsp { get; set; }
        public Nullable<bool> Defecto { get; set; }
        public string Pais { get; set; }
        public string Banco { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> BSP { get; set; }
    }
}
