//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasCabeceraTotales
    {
        public int grupo { get; set; }
        public Nullable<decimal> contado1 { get; set; }
        public Nullable<decimal> credito1 { get; set; }
        public Nullable<decimal> canjes1 { get; set; }
        public Nullable<decimal> ctacje1 { get; set; }
        public Nullable<decimal> tarifa1 { get; set; }
        public Nullable<decimal> igvtarifa1 { get; set; }
        public Nullable<decimal> otingreso1 { get; set; }
        public Nullable<decimal> otrosimp1 { get; set; }
        public Nullable<decimal> otcredito1 { get; set; }
        public Nullable<decimal> comision1 { get; set; }
        public Nullable<decimal> igvcomision1 { get; set; }
        public Nullable<int> tickets1 { get; set; }
        public Nullable<int> pta1 { get; set; }
        public Nullable<int> void1 { get; set; }
        public Nullable<int> totaltkt1 { get; set; }
        public Nullable<decimal> contado2 { get; set; }
        public Nullable<decimal> credito2 { get; set; }
        public Nullable<decimal> canjes2 { get; set; }
        public Nullable<decimal> ctacje2 { get; set; }
        public Nullable<decimal> ctacje { get; set; }
        public Nullable<decimal> tarifa2 { get; set; }
        public Nullable<decimal> igvtarifa2 { get; set; }
        public Nullable<decimal> otingreso2 { get; set; }
        public Nullable<decimal> otrosimp2 { get; set; }
        public Nullable<decimal> otcredito2 { get; set; }
        public Nullable<decimal> otcredito { get; set; }
        public Nullable<decimal> comision2 { get; set; }
        public Nullable<decimal> igvcomision2 { get; set; }
        public Nullable<int> tickets2 { get; set; }
        public Nullable<int> pta2 { get; set; }
        public Nullable<int> void2 { get; set; }
        public Nullable<int> totaltkt2 { get; set; }
        public Nullable<decimal> deposito1 { get; set; }
        public Nullable<decimal> deposito2 { get; set; }
        public Nullable<decimal> facturas1 { get; set; }
        public Nullable<decimal> facturas2 { get; set; }
        public Nullable<decimal> ncredito { get; set; }
        public Nullable<int> con_num_dep_gen { get; set; }
        public Nullable<decimal> con_imp_dep_gen { get; set; }
        public Nullable<int> con_num_dep_rec { get; set; }
        public Nullable<decimal> con_imp_dep_rec { get; set; }
        public Nullable<int> con_num_fac_gen { get; set; }
        public Nullable<decimal> con_imp_fac_gen { get; set; }
        public Nullable<int> con_num_fac_rec { get; set; }
        public Nullable<decimal> con_imp_fac_rec { get; set; }
        public Nullable<decimal> acmapli { get; set; }
        public Nullable<decimal> acmemit { get; set; }
        public Nullable<decimal> admapli { get; set; }
        public Nullable<decimal> admemit { get; set; }
        public Nullable<decimal> tarjeta1 { get; set; }
        public Nullable<decimal> tarjeta2 { get; set; }
        public Nullable<decimal> gastos { get; set; }
        public Nullable<decimal> reembolso { get; set; }
        public Nullable<decimal> difere { get; set; }
        public Nullable<decimal> ajuste { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<System.DateTime> fechareg { get; set; }
    
        public virtual VentasCabecera VentasCabecera { get; set; }
    }
}
