//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasCabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VentasCabecera()
        {
            this.VentasBoletos = new HashSet<VentasBoletos>();
            this.VentasCabecera_Log = new HashSet<VentasCabecera_Log>();
            this.VentasCabeceraNotas = new HashSet<VentasCabeceraNotas>();
        }
    
        public int Grupo { get; set; }
        public string Pais { get; set; }
        public string Origen { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Ciclo { get; set; }
        public Nullable<byte> Estado { get; set; }
        public Nullable<int> Agente { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
        public Nullable<System.DateTime> FechaContable { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public string PeriodoReporte { get; set; }
        public Nullable<int> NroTkts { get; set; }
        public Nullable<int> NroPtas { get; set; }
        public Nullable<int> NroVoids { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<decimal> IgvComision { get; set; }
        public Nullable<decimal> Contado { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<decimal> Canje { get; set; }
        public Nullable<decimal> OtrosCargos { get; set; }
        public Nullable<decimal> Tarifa { get; set; }
        public Nullable<decimal> IgvTarifa { get; set; }
        public Nullable<decimal> OtrosImp { get; set; }
        public Nullable<decimal> OtrosIngresos { get; set; }
        public Nullable<decimal> OtrasComisiones { get; set; }
        public Nullable<decimal> OtrosCreditos { get; set; }
        public Nullable<decimal> OtrosTax { get; set; }
        public Nullable<decimal> SaldoDepo { get; set; }
        public Nullable<decimal> SaldoFactu { get; set; }
        public string Remark { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string UsuarioPrecierre { get; set; }
        public Nullable<System.DateTime> FechaPrecierre { get; set; }
        public string UsuarioConta { get; set; }
        public Nullable<System.DateTime> Fechaconta { get; set; }
        public string Notas { get; set; }
        public Nullable<decimal> venta_contado { get; set; }
        public Nullable<decimal> venta_credito { get; set; }
        public Nullable<decimal> venta_directa { get; set; }
        public Nullable<decimal> venta_indirecta { get; set; }
        public Nullable<bool> Abierto { get; set; }
        public string UsuarioCierre { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string noReportado { get; set; }
        public Nullable<decimal> Ajustes { get; set; }
        public Nullable<decimal> SaldoFinal { get; set; }
        public Nullable<bool> F1 { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
    
        public virtual Agentes Agentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasBoletos> VentasBoletos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasCabecera_Log> VentasCabecera_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasCabeceraNotas> VentasCabeceraNotas { get; set; }
        public virtual VentasCabeceraTotales VentasCabeceraTotales { get; set; }
    }
}
