//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public int IdVuelo { get; set; }
        public string Itinerario { get; set; }
        public Nullable<System.DateTime> FechaVuelo { get; set; }
        public string Vuelo { get; set; }
        public string Orden { get; set; }
        public string Carrier { get; set; }
        public string NroVuelo { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public Nullable<System.DateTime> HoraLlegada { get; set; }
        public string LocOrigen { get; set; }
        public string LocDestino { get; set; }
        public string Stop { get; set; }
        public Nullable<short> TipoVuelo { get; set; }
        public string Equipo { get; set; }
        public string Matricula { get; set; }
        public Nullable<short> PaxADL { get; set; }
        public Nullable<short> PaxCHD { get; set; }
        public Nullable<short> PaxINF { get; set; }
        public Nullable<short> PaxFree { get; set; }
        public Nullable<short> PaxINT { get; set; }
        public Nullable<short> PaxTotal { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public Nullable<byte> Estado { get; set; }
        public string UsuarioCierre { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string UsuarioConta { get; set; }
        public Nullable<System.DateTime> FechaConta { get; set; }
        public string Notas { get; set; }
        public string NotasCierre { get; set; }
        public Nullable<System.DateTime> FechaContable { get; set; }
    }
}
